name: emocaps
channels:
- conda-forge
- plotly
dependencies:
- python=3.7
- pip
- numpy
- scipy
- matplotlib
- pandas
- numba
- cudatoolkit=10.1
- cudnn=7.6
- tensorflow-gpu=2.3
- tensorflow-estimator=2.3
- xlrd
- scikit-learn
- h5py
- pillow
- statsmodels
- jupyter
- joblib
- psutil
- numexpr
- imageio
- tqdm
- spyder-kernels>=1.10.0
- imageio-ffmpeg>=0.4.1
- vtk>=9.0.1
- pyvista>=0.30
- pyvistaqt>=0.4
- qdarkstyle
- darkdetect
- mayavi
- PySurfer
- dipy
- nibabel
- nilearn
- python-picard
- pyqt!=5.15.3
- mne
- mffpy>=0.5.7
- ipywidgets
- plotly
- pip:
  - ipyvtklink
  - tensorflow-addons
  - openpyxl
  - opencv-python
  - pytest
  - pygame
  - open3d
